name: Build and release
on:
  push:
    branches:
      - main

jobs:
  bump-version:
    name: Release version
    runs-on: ubuntu-latest

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: citations_test
          extra-files: |
            CITATION.cff